development:
  adapter: mysql2
  encoding: utf8
  username: root
  password: 0402Jonas
  port: 3306
  database: hello_amp_development

test:
  adapter: mysql2
  encoding: utf8
  username: root
  password: 0402Jonas
  port: 3306
  database: hello_amp_test
